version: '3.3'
  
services:
  tpc-db:
    image: mysql:8.0.17
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=tpc
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_SOCKET_DIR="/var/lib/mysql/sock"
    ports:
      - "3306:3306"
    volumes:
      - /data/db/tpc:/var/lib/mysql
      - ${PWD}/conf.d:/etc/mysql/conf.d
