apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: data-path1
spec:
  config: '{
          "cniVersion": "0.4.0",
          "plugins": [
            {
              "type": "macvlan",
              "capabilities": { "ips": true },
              "master": "enp129s0f0np0",
              "mode": "bridge",
              "ipam": {
                "type": "static",
                "addresses": [
                  {
                    "address": "192.78.1.101/24"
                  }
                ]
              }
            }
          ]    
  }'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tpc-db1
  labels:
    app: tpc-db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tpc-db1
  template:
    metadata:
      annotations:
        k8s.v1.cni.cncf.io/networks: data-path1
      labels:
        app: tpc-db1
    spec:
      containers:
      - name: tpc-db1
        image: mysql:8.0.31
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_DATABASE
            value: tpc
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_ROOT_PASSWORD
            value: password
          - name: MYSQL_SOCKET_DIR
            value: '"/var/lib/mysql/sock"'
        volumeMounts:
          - name: tpc-db1-conf
            mountPath: /etc/mysql/conf.d
          - name: tpc-db1-vol
            mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: tpc-db1-conf
          hostPath:
            path: /mnt/conf.d
        - name: tpc-db1-vol
          hostPath:
            path: /mnt/db1
---
apiVersion: v1
kind: Service
metadata:
  name: tpc-db1
spec:
  type: NodePort
  ports:
    - name: "db1"
      protocol: TCP
      port: 3306
      nodePort: 30001
      targetPort: 3306
  selector:
    app: tpc-db1
